### ISSUE TITLE
AGO

### ISSUE THREAD

**Issue by NedaJalali-codes** [HopkinsIDD/cholera-mapping-pipeline#201]
Error details: 
```
Quitting from lines 315-316 (country_data_report.Rmd) 
Error:
! Assigned data `cache[["grid_cases_mean_by_chain"]]` must be compatible with existing data.
✖ Existing data has 4365 rows.
✖ Element 1 of assigned data has 4335 rows.
ℹ Only vectors of size 1 are recycled.
Backtrace:
  1. taxdat::table_modeled_cases_by_chain_time(...)
 13. tibble `<fn>`(`<vctrs___>`)
```

Config: 
```
general:
  location_name: AFR::AGO
  start_date: '2016-01-01'
  end_date: '2020-12-31'
  width_in_km: 20.0
  height_in_km: 20.0
  time_scale: year
  covariates: 
   - name: "population"
stan:
  directory: /home/njalali2/Cholera_jh/cholera-mapping-pipeline-new-pipeline/Analysis/Stan
  ncores: 2.0
  model: dagar_seasonal_flexible.stan
  niter: 1000.0
  recompile: yes
file_names:
  stan_output: /home/njalali2/Cholera_jh/cholera-mapping-pipeline-new-pipeline/Analysis/output/test.stan_output.rds
  stan_input: /home/njalali2/Cholera_jh/cholera-mapping-pipeline-new-pipeline/Analysis/output/test.stan_input.rdata
processing:
  average_inconsistent_duplicates: no
  remove_overlaps: 
    perform: yes
```

Batch file: 

```
#!/bin/bash
#SBATCH --job-name=new_pipeline
#SBATCH --output=logs/new_pipeline_AGO.txt
#SBATCH --time=10000:00:00
#SBATCH --mem=50G
#SBATCH --nodelist=idmodeling2
#SBATCH -c 4

echo "Beginning of script"
date
export CHOLERA_POSTGRES_PORT=5435
export CHOLERA_POSTGRES_DATABASE=cholera_testing_database
choleraDir=/home/njalali2/Cholera_jh/cholera-mapping-pipeline-new-pipeline
CONFIG=$1
RSCRIPT=/opt/R/4.0.3/bin/Rscript

cd $choleraDir

$RSCRIPT $choleraDir/Analysis/R/execute_pipeline.R -c $choleraDir/Analysis/R/config_AGO.yml || exit 1
echo "End of script"
date
```

Initial run date: 
09/16/2022
