### ISSUE TITLE
GHA

### ISSUE THREAD

**Issue by NedaJalali-codes** [HopkinsIDD/cholera-mapping-pipeline#204]
Error details: 

```
Quitting from lines 238-239 (country_data_report.Rmd) 
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 2395, 1175
Calls: <Anonymous> ... as.data.frame -> as.data.frame.list -> do.call -> <Anonymous>
```

Config details: 
```
general:
  location_name: AFR::GHA
  start_date: '2016-01-01'
  end_date: '2020-12-31'
  width_in_km: 20.0
  height_in_km: 20.0
  time_scale: year
  covariates: 
   - name: "population"
stan:
  directory: /home/njalali2/Cholera_jh/cholera-mapping-pipeline-new-pipeline/Analysis/Stan
  ncores: 2.0
  model: dagar_seasonal_flexible.stan
  niter: 1000.0
  recompile: yes
file_names:
  stan_output: /home/njalali2/Cholera_jh/cholera-mapping-pipeline-new-pipeline/Analysis/output/test.stan_output.rds
  stan_input: /home/njalali2/Cholera_jh/cholera-mapping-pipeline-new-pipeline/Analysis/output/test.stan_input.rdata
processing:
  average_inconsistent_duplicates: no
  remove_overlaps: 
    perform: yes
```

Batch file:
```
#!/bin/bash
#SBATCH --job-name=new_pipeline
#SBATCH --output=logs/new_pipeline_GHA.txt
#SBATCH --time=10000:00:00
#SBATCH --mem=20G
#SBATCH --nodelist=idmodeling2
#SBATCH -c 4

echo "Beginning of script"
date
export CHOLERA_POSTGRES_PORT=5435
export CHOLERA_POSTGRES_DATABASE=cholera_testing_database
choleraDir=/home/njalali2/Cholera_jh/cholera-mapping-pipeline-new-pipeline
CONFIG=$1
RSCRIPT=/opt/R/4.0.3/bin/Rscript

cd $choleraDir

$RSCRIPT $choleraDir/Analysis/R/execute_pipeline.R -c $choleraDir/Analysis/R/config_GHA.yml || exit 1
echo "End of script"
date
```

Initial run date: 09/19/2022
